#!/usr/bin/env python3
"""Decompilation progress: functions/bytes in src/*.c vs all code.

  progress.py            human-readable summary
  progress.py --json F   objdiff-style report (schema-ish v2) for decomp.dev
  progress.py --markdown F   PROGRESS.md tracker (per-region bars)
"""
import json
import re
import sys

from romlib import ROOT
from split import c_functions
import glob
import os


def main():
    code = open(os.path.join(ROOT, "gen", "code_sym.s")).read()
    funcs = [(n, int(a, 16)) for n, a in re.findall(r"^(\w+): @ 0x([0-9A-F]{8})", code, re.M)]
    funcs.sort(key=lambda x: x[1])
    code_end = 0x0824DAFA
    sizes = {}
    for (n, a), nxt in zip(funcs, funcs[1:] + [(None, code_end)]):
        sizes[n] = nxt[1] - a
    done = set()
    for p in glob.glob(os.path.join(ROOT, "src", "**", "*.c"), recursive=True):
        done |= set(c_functions(p, with_asm=False))
    total_b = sum(sizes.values())
    done_b = sum(sizes.get(n, 0) for n in done)
    print(f"functions: {len(done)}/{len(funcs)} ({100 * len(done) / len(funcs):.2f}%)")
    print(f"code bytes: {done_b}/{total_b} ({100 * done_b / total_b:.3f}%)")
    if "--markdown" in sys.argv:
        out = sys.argv[sys.argv.index("--markdown") + 1]
        write_markdown(out, funcs, sizes, done, total_b, done_b)
    if "--json" in sys.argv:
        out = sys.argv[sys.argv.index("--json") + 1]
        rep = {"measures": {
            "total_code": str(total_b), "matched_code": str(done_b),
            "matched_code_percent": 100 * done_b / total_b,
            "total_functions": len(funcs), "matched_functions": len(done),
            "matched_functions_percent": 100 * len(done) / len(funcs),
            "complete_code": str(done_b), "complete_code_percent": 100 * done_b / total_b,
        }, "units": []}
        json.dump(rep, open(out, "w"), indent=1)


def bar(frac, width=30):
    n = round(frac * width)
    return "█" * n + "░" * (width - n)


def write_markdown(out, funcs, sizes, done, total_b, done_b):
    regions = [(0x08000000, 0x08040000), (0x08040000, 0x08080000), (0x08080000, 0x080C0000),
               (0x080C0000, 0x08100000), (0x08100000, 0x08140000), (0x08140000, 0x08180000),
               (0x08180000, 0x081C0000), (0x081C0000, 0x08200000), (0x08200000, 0x08240000),
               (0x08240000, 0x0824DAFA)]
    lines = ["# Decompilation progress", "",
             "Generated by `python3 tools/progress.py --markdown PROGRESS.md`.", "",
             f"**Code matched in C: {100 * done_b / total_b:.2f}%** "
             f"({done_b:,} / {total_b:,} bytes) — **{len(done)} / {len(funcs)} functions**", "",
             "```", f"{bar(done_b / total_b, 50)} {100 * done_b / total_b:.2f}%", "```", "",
             "| Region | Functions | Matched | Bytes matched | |", "|---|---:|---:|---:|---|"]
    for lo, hi in regions:
        fs = [(n, a) for n, a in funcs if lo <= a < hi]
        tb = sum(sizes[n] for n, _ in fs)
        db = sum(sizes[n] for n, _ in fs if n in done)
        nd = sum(1 for n, _ in fs if n in done)
        if not fs:
            continue
        lines.append(f"| `{lo:08X}–{hi:08X}` | {len(fs)} | {nd} | {100 * db / max(tb, 1):.1f}% | `{bar(db / max(tb, 1), 20)}` |")
    open(out, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
